### PR TITLE
Assert that an instanciated PrivateKey is usable

### PR DESCRIPTION
**Pull request by richo**
Include a test for validity of an instanciated PrivateKey

### CODE REVIEW

**Comment by pda** [comment]
Rebased onto master;

- Ported test to PHPUnit.
- Ran `php-cs-fixer` over test.
- Corrected whitespace for `Relax_Openssl_PrivateKey::isValid()`

**Comment by pda** [comment]
Rebased onto master;

- Ported test to PHPUnit.
- Ran `php-cs-fixer` on `tests/Relax/Openssl/PrivateKeyTest.php`.
- Corrected whitespace for `Relax_Openssl_PrivateKey::isValid()`.

Note that [commerce master at the time I'm writing this](https://github.com/99designs/commerce/commit/1585bce7881a45f2936e161f3435daf49966599f) is depending on this `features/test_is_valid` branch via the https://github.com/99designs/relax/tree/844a2468537526ac9db43960ceef5749df674d1b commit, which has since been rebased away.

/cc @lox

**Comment by pda** [comment]
Fixing this multi-year version stalemate:

* https://github.com/99designs/relax/pull/3
* https://github.com/99designs/ergo/pull/22

**Comment by richo** [comment]
Amazing! \o/

**Pull request merged**
